include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_element: false
    unused_element_parameter: error
    unused_local_variable: error
    unused_field: false
    

linter:
  rules: 
    constant_identifier_names: false



